name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pygbag
        run: pip install pygbag

      - name: Build WebAssembly Version
        run: python -m pygbag --build .

      - name: Post-build HTML Adjustments
        run: |
          sed -i 's/background-color:powderblue;/background-color:black;/g' build/web/index.html


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
